spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pulluankur/spring-cloud-config-server
server:
  port: 8888
