spring:
  application:
    name: curreny-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
