spring:
  application:
    name: curreny-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    stream:
      bindings:
        consumer:
          destination: consumer
          group: consumer-group
      default-binder: rabbit
server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
